export interface Product {
  id: string
  name: string
  description: string
  price: number
  originalPrice: number | null
  category: string
  size: string
  sizes: string[]
  color: string
  colors: string[]
  badge: string | null
  inStock: boolean
  specifications: {
    material: string
    weight: string
    closure: string
    packSize: string
  }
}

export const products: Product[] = [
  {
    id: "1",
    name: "Colour Board Coin",
    description: "Premium quality colour board coin envelopes. Perfect for traditional gifting and shagun ceremonies.",
    price: 260,
    originalPrice: null,
    category: "coin",
    size: "Standard",
    sizes: ["Standard"],
    color: "Multi",
    colors: ["10 Colours"],
    badge: "Wholesale",
    inStock: true,
    specifications: {
      material: "Premium Colour Board",
      weight: "Standard",
      closure: "Traditional Flap",
      packSize: "100 pcs per box",
    },
  },
  {
    id: "2",
    name: "Screen Printing Plain",
    description: "Classic screen printed plain envelopes for elegant and traditional shagun gifting.",
    price: 125,
    originalPrice: null,
    category: "plain-printed",
    size: "Standard",
    sizes: ["Standard"],
    color: "Multi",
    colors: ["2 Colours"],
    badge: "Legacy Since 1990s",
    inStock: true,
    specifications: {
      material: "Screen Printed Paper",
      weight: "Standard",
      closure: "Gummed Flap",
      packSize: "100 pcs per box",
    },
  },
  {
    id: "3",
    name: "Screen Printing Coin",
    description: "Traditional screen printed coin envelopes, ideal for weddings and religious ceremonies.",
    price: 450,
    originalPrice: null,
    category: "coin",
    size: "Standard",
    sizes: ["Standard"],
    color: "Multi",
    colors: ["2 Colours"],
    badge: "Popular",
    inStock: true,
    specifications: {
      material: "Premium Screen Printed Paper",
      weight: "Heavy",
      closure: "Traditional Flap",
      packSize: "100 pcs per box",
    },
  },
  {
    id: "4",
    name: "One Shot Coin",
    description: "Modern one-shot design coin envelopes available in vibrant traditional colours.",
    price: 400,
    originalPrice: null,
    category: "coin",
    size: "Standard",
    sizes: ["Standard"],
    color: "Multi",
    colors: ["5 Colours"],
    badge: "New",
    inStock: true,
    specifications: {
      material: "One Shot Design Paper",
      weight: "Standard",
      closure: "Easy Close",
      packSize: "100 pcs per box",
    },
  },
  {
    id: "5",
    name: "One Shot Plain",
    description: "Elegant one-shot plain envelopes for a clean and sophisticated presentation.",
    price: 250,
    originalPrice: null,
    category: "plain-printed",
    size: "Standard",
    sizes: ["Standard"],
    color: "Multi",
    colors: ["5 Colours"],
    badge: null,
    inStock: true,
    specifications: {
      material: "One Shot Design Paper",
      weight: "Standard",
      closure: "Easy Close",
      packSize: "100 pcs per box",
    },
  },
  {
    id: "6",
    name: "Fancy Dori Envelope",
    description: "Exquisite fancy dori envelopes with traditional thread closures for luxury gifting.",
    price: 425,
    originalPrice: null,
    category: "fancy",
    size: "Premium",
    sizes: ["Premium"],
    color: "Multi",
    colors: ["5 Colours"],
    badge: "Luxury",
    inStock: true,
    specifications: {
      material: "Handcrafted Paper",
      weight: "Heavy",
      closure: "Dori (Thread)",
      packSize: "100 pcs per box",
    },
  },
  {
    id: "7",
    name: "Pocket Envelope",
    description: "Versatile pocket-style envelopes suitable for various gifting and traditional uses.",
    price: 225,
    originalPrice: null,
    category: "fancy",
    size: "Pocket",
    sizes: ["Pocket"],
    color: "Multi",
    colors: ["5 Colours"],
    badge: null,
    inStock: true,
    specifications: {
      material: "Quality Paper Board",
      weight: "Standard",
      closure: "Pocket Flap",
      packSize: "100 pcs per box",
    },
  },
  {
    id: "8",
    name: "Note Envelope",
    description: "Premium note envelopes for high-value shagun and special occasions.",
    price: 875,
    originalPrice: null,
    category: "fancy",
    size: "Note",
    sizes: ["Note"],
    color: "Multi",
    colors: ["3 Colours"],
    badge: "Executive",
    inStock: true,
    specifications: {
      material: "Premium Textured Paper",
      weight: "Extra Heavy",
      closure: "Premium Flap",
      packSize: "100 pcs per box",
    },
  },
  {
    id: "9",
    name: "Gaddi Box Envelope",
    description: "Luxury Gaddi box envelopes for premium currency gifting and ceremonial use.",
    price: 200,
    originalPrice: null,
    category: "gaddi",
    size: "Gaddi",
    sizes: ["Gaddi"],
    color: "Multi",
    colors: ["5 Colours"],
    badge: "Premium Box",
    inStock: true,
    specifications: {
      material: "Luxury Board",
      weight: "Heavy Duty",
      closure: "Box Style",
      packSize: "10 pcs per box",
    },
  },
  {
    id: "10",
    name: "Single Envelope",
    description: "High-end single envelopes for exclusive and personalized gifting.",
    price: 1000,
    originalPrice: null,
    category: "fancy",
    size: "Exclusive",
    sizes: ["Exclusive"],
    color: "Multi",
    colors: ["5 Colours"],
    badge: "High Value",
    inStock: true,
    specifications: {
      material: "Exclusive Premium Paper",
      weight: "Ultra Heavy",
      closure: "Designer Flap",
      packSize: "25 pcs per box",
    },
  },
  {
    id: "11",
    name: "Plain Stand Envelope",
    description: "Sturdy plain stand envelopes for traditional display and gifting.",
    price: 175,
    originalPrice: null,
    category: "plain-printed",
    size: "Stand",
    sizes: ["Stand"],
    color: "Multi",
    colors: ["5 Colours"],
    badge: null,
    inStock: true,
    specifications: {
      material: "Stand Quality Board",
      weight: "Stiff",
      closure: "Stand Flap",
      packSize: "100 pcs per box",
    },
  },
  {
    id: "12",
    name: "Gaddi Box Red & Maroon",
    description: "Premium red and maroon Gaddi box envelopes, perfect for weddings and festivities.",
    price: 2000,
    originalPrice: null,
    category: "gaddi",
    size: "Premium Gaddi",
    sizes: ["Premium Gaddi"],
    color: "Red/Maroon",
    colors: ["Red", "Maroon"],
    badge: "Festive Collection",
    inStock: true,
    specifications: {
      material: "Luxury Velvet/Board",
      weight: "Extra Heavy",
      closure: "Box Style",
      packSize: "10 pcs per box",
    },
  },
  {
    id: "13",
    name: "Gaddi Box Laser Rose",
    description: "Exquisite laser-cut rose design Gaddi box envelopes for a touch of elegance.",
    price: 2000,
    originalPrice: null,
    category: "gaddi",
    size: "Premium Gaddi",
    sizes: ["Premium Gaddi"],
    color: "Multi",
    colors: ["3 Colours"],
    badge: "Designer Piece",
    inStock: true,
    specifications: {
      material: "Laser Cut Premium Board",
      weight: "Heavy",
      closure: "Box Style",
      packSize: "10 pcs per box",
    },
  },
  {
    id: "14",
    name: "Gaddi Box Leaf",
    description: "Elegant leaf design Gaddi box envelopes combining tradition with modern aesthetics.",
    price: 1000,
    originalPrice: null,
    category: "gaddi",
    size: "Gaddi",
    sizes: ["Gaddi"],
    color: "Multi",
    colors: ["5 Colours"],
    badge: null,
    inStock: true,
    specifications: {
      material: "Quality Board with Leaf Motif",
      weight: "Heavy",
      closure: "Box Style",
      packSize: "10 pcs per box",
    },
  },
  {
    id: "15",
    name: "Off Side Plain Stand",
    description: "Minimalist off-side design plain stand envelopes for a modern traditional look.",
    price: 125,
    originalPrice: null,
    category: "plain-printed",
    size: "Stand",
    sizes: ["Stand"],
    color: "Single",
    colors: ["1 Colour"],
    badge: "Budget Friendly",
    inStock: true,
    specifications: {
      material: "Economy Board",
      weight: "Standard",
      closure: "Stand Flap",
      packSize: "100 pcs per box",
    },
  },
]

export const categories = [
  { id: "all", name: "All Products" },
  { id: "coin", name: "Coin Envelopes" },
  { id: "plain-printed", name: "Plain & Printed" },
  { id: "fancy", name: "Fancy / Dori / Pocket" },
  { id: "gaddi", name: "Gaddi Box (Premium)" },
]

export const sizes = ["Standard", "Premium", "Pocket", "Note", "Gaddi", "Exclusive", "Stand"]
export const colors = ["10 Colours", "5 Colours", "3 Colours", "2 Colours", "Red", "Maroon", "Single"]
export const priceRanges = [
  { label: "Under ₹250", min: 0, max: 250 },
  { label: "₹250 - ₹500", min: 250, max: 500 },
  { label: "₹500 - ₹1000", min: 500, max: 1000 },
  { label: "Above ₹1000", min: 1000, max: 5000 },
]
